<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Parameter -->
    <xacro:property name="camera_length" value="0.01" />
    <xacro:property name="camera_width" value="0.1" />
    <xacro:property name="camera_height" value="0.05" />
    <xacro:property name="camera_mass" value="0.1" />

    <!-- Camera Link -->
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
        </collision>
        <xacro:box_inertia m="${camera_mass}" 
                          x="${camera_length}" 
                          y="${camera_width}" 
                          z="${camera_height}"
                          o_xyz="0 0 0" 
                          o_rpy="0 0 0" />
    </link>

    <!-- Joint to base -->
    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
        <origin xyz="${(base_length + camera_length)/2.0} 0 ${base_height/2.0}" rpy="0 0 0" />
    </joint>

    <!-- Optical Frame (REP-103/REP-105 compliant) -->
    <link name="camera_link_optical" />

    <joint name="camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
    </joint>

    <!-- Gazebo Sensor Configuration -->
    <gazebo reference="camera_link">
        <sensor name="camera_sensor" type="camera">
            <camera>
                <horizontal_fov>1.3962634</horizontal_fov> <!-- ~80 degrees -->
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>15</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </camera>
            <always_on>true</always_on>
            <update_rate>30</update_rate> <!-- Empfohlene Framerate -->
            <visualize>true</visualize>
            
            <!-- ROS Integration -->
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <ros>
                    <namespace>/camera</namespace>
                </ros>
                <camera_name>camera</camera_name>
                <frame_name>camera_link_optical</frame_name>
                <hack_baseline>0.07</hack_baseline>
            </plugin>
        </sensor>
    </gazebo>
</robot>