<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Robot Base-->
    <xacro:property name="base_length" value="0.4" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="1" />
    <xacro:property name="wheel_radius" value="0.075" />
    <xacro:property name="wheel_length" value="0.04" />


    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <mesh filename="package://telerobot_description/meshes/Mosro.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin xyz="0 0 ${base_height}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${base_width / 2.0}" length="${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="1.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    <joint name="base_to_base_footprint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 ${3.14159/2.0} 0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 ${3.14159/2.0} 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}"
                               xyz="0 ${base_width / 2.0} ${wheel_radius}" rpy="0 ${-3.14159 / 2.0} 0" />
    </link>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_width / 2.0 + 0.05} 0 0" rpy="0 0 0" />
        <axis xyz="1 0 0" />
    </joint>

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 ${3.14159/2.0} 0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 ${3.14159/2.0} 0"  />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}"
                               xyz="0 ${-base_width / 2.0} ${wheel_radius}" rpy="0 ${-3.14159 / 2.0} 0" />
    </link>
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${base_width / 2.0-0.05} 0 0" rpy="0 0 0" />
        <axis xyz="1 0 0" />
    </joint>
    

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius+0.015}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius+0.015}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:sphere_inertia m="1.0" r="${2*wheel_radius / 2.0}"
                              xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="0 ${base_width / 2.0} 0.015" rpy="0 0 0" />
    </joint>

</robot>