- ros_topic_name: "clock"
  gz_topic_name: "ignition.msgs.Clock"
  ros_type_name: ""
  gz_type_name: ""
  direction: ""

- ros_topic_name: ""
  gz_topic_name: ""
  ros_type_name: ""
  gz_type_name: ""
  direction: ""

- ros_topic_name: ""
  gz_topic_name: ""
  ros_type_name: ""
  gz_type_name: ""
  direction: ""

- ros_topic_name: ""
  gz_topic_name: ""
  ros_type_name: ""
  gz_type_name: ""
  direction: ""

- ros_topic_name: ""
  gz_topic_name: ""
  ros_type_name: ""
  gz_type_name: ""
  direction: ""